language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t m-jarmula/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true m-jarmula/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-625851814065"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
